### ISSUE TITLE
Can't access project website

### ISSUE THREAD

**Issue by RubenVerborgh** [cgueret/eRDF#5]
Hi Christophe,

Paul Groth pointed me to this repository and I'm curious to find out more.
Unfortunately, the website http://www.erdf.nl/ isn't accessible.
Could you have a look at that?

Thanks,

Ruben

**Comment by cgueret** [comment]
Oh, this is weird... can't have a close look right now but I'll be on it
asap.
Thanks for being interested in eRDF!

Christophe

On 12 March 2014 10:36, Ruben Verborgh notifications@github.com wrote:

> Hi Christophe,
> 
> Paul Groth pointed me to this repository and I'm curious to find out more.
> Unfortunately, the website http://www.erdf.nl/ isn't accessible.
> Could you have a look at that?
> 
> Thanks,
> 
> Ruben
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cgueret/eRDF/issues/5
> .

## 

Onderzoeker
+31(0)6 14576494
christophe.gueret@dans.knaw.nl

_Data Archiving and Networked Services (DANS)_

DANS bevordert duurzame toegang tot digitale onderzoeksgegevens. Kijk op
www.dans.knaw.nl voor meer informatie. DANS is een instituut van KNAW en
NWO.

Let op, per 1 januari hebben we een nieuw adres:

DANS | Anna van Saksenlaan 51 | 2593 HW Den Haag | Postbus 93067 | 2509 AB
Den Haag | +31 70 349 44 50 | info@dans.knaw.nl info@dans.kn |
www.dans.knaw.nl

_Let's build a World Wide Semantic Web!_
http://worldwidesemanticweb.org/

_e-Humanities Group (KNAW)_
[image: eHumanities] http://www.ehumanities.nl/

**Comment by cgueret** [comment]
Fixed! See http://cgueret.github.io/eRDF/
Thanks again for the notification

**Comment by RubenVerborgh** [comment]
Thanks, it's an interesting read :-)
